---
name: Build RPI Img
kind: pipeline
type: docker

trigger:
  event:
    - tag

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: sofianinho/dind
  commands:
    - bash -c "rpi/build.sh"