---
name: Build RPI Img
kind: pipeline
type: docker

trigger:
  event:
    - tag

steps:
- name: build
  image: billyteves/ubuntu-dind
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  commands:
    - bash -c "rpi/build.sh"

# - name: docker  
#   image: plugins/docker
#   settings:
#     repo: bootlegger/titan-compact
#     dockerfile: docker/titan/Dockerfile
#     auto_tag: true
#     tags:
#       - latest
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#     build_args:
#       - TARGETPLATFORM=linux/arm/v7
#     context: docker/titan/
