# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        filePath: './rpi/build.sh'
        workingDirectory: './rpi/'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: './rpi/pi-gen/deploy'
        artifactName: disk-image